student_api/crud/urls.py
# students/urls.py
from django.urls import path, include
from .views import ItemListView, ItemDetailView, ItemCreateView, ItemUpdateView, ItemDeleteView

urlpatterns = [

    path('', ItemListView.as_view(), name='item_list'),
    path('item/<int:pk>/', ItemDetailView.as_view(), name='item_detail'),
    path('item/new/', ItemCreateView.as_view(), name='item_create'),
    path('item/<int:pk>/edit/', ItemUpdateView.as_view(), name='item_update'),
    path('item/<int:pk>/delete/', ItemDeleteView.as_view(), name='item_delete'),
]

student_api/student_api/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('students.urls')),
    path('', include('crud.urls'))
]

student_api/students/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

]

student_api/crud/models.py
from django.db import models

# Create your models here.

app_name = 'crud'


class Item(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=100)
    image = models.ImageField(upload_to='media/', blank=True, null=True)

    def __str__(self):
        return self.name

student_api/students/models.py
from django.db import models


# Create your models here.
class Student(models.Model):
    name = models.CharField(max_length=100)
    student_id = models.CharField(max_length=10, unique=True)
    photo = models.ImageField(upload_to='media/', blank=True, null=True)


    def __str__(self):
        return self.name

student_api/crud/forms.py
from django import forms
from .models import Item


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['name', 'description']

student_api/crud/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Item
from .forms import ItemForm
from django.urls import reverse_lazy


class ItemListView(ListView):
    model = Item
    template_name = 'crud/item_list.html'
    context_object_name = 'object'



class ItemDetailView(DetailView):
    model = Item
    template_name = 'crud/item_detail.html'
    context_object_name = 'item'


class ItemCreateView(CreateView):
    model = Item
    form_class = ItemForm
    template_name = 'crud/item_form.html'
    success_url = reverse_lazy('item_list')


class ItemUpdateView(UpdateView):
    model = Item
    form_class = ItemForm
    template_name = 'crud/item_form.html'
    context_object_name = 'item'
    success_url = reverse_lazy('item_list')


class ItemDeleteView(DeleteView):
    model = Item
    template_name = 'crud/item_confirm_delete.html'
    context_object_name = 'item'
    success_url = reverse_lazy('item_list')


# Create your views here.

student_api/crud/templates/crud/item_form.html
<!DOCTYPE html>
<html>
<head>
    <title>Create/Update Item</title>
</head>
<body>
    <h1>Create/Update Item</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <label for="id_photo">Choose Photo:</label>
        <input type="file" name="photo" id="id_photo">
        <button type="submit">Save</button>
    </form>
    <a href="{% url 'item_list' %}">Back to Item List</a>
</body>
</html>

student_api/crud/templates/crud/item_list.html
<!DOCTYPE html>
<html>
<head>
    <title>Item List</title>
</head>
<body>
    <h1>Item List</h1>
    <ul>

        {% for item in object %}
            <li>{{ item.id }}</li>
            <li>{{ item.name}}</li>

        {% empty %}
            <li>No items available.</li>
        {% endfor %}

    </ul>
    <a href="{% url 'item_create' %}">Create New Item</a>
</body>
</html>